apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: diwise-web
    includeSelectors: true

resources:
- ../../base/

patches:
- path: patches/image.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: diwise-web
