apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    opentelemetry: enabled
  name: diwise-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTROL_PORT
          value: "8000"
        - name: CONTENT_SECURITY_POLICY
          value: "report"
        - name: OAUTH2_REALM_URL
          valueFrom:
            secretKeyRef:
              name: authn-oauth2-par
              key: realm-url
        - name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: authn-oauth2-par
              key: client-id
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authn-oauth2-par
              key: client-secret
        image: ghcr.io/diwise/diwise-web:changeme
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: control-port
        name: diwise-web
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        - containerPort: 8000
          name: control-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: control-port
      serviceAccountName: diwise-web
